django0605/config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('diary.urls')),
]

django0605/diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'
urlpatterns =[
    path('index/',views.IndexView.as_view(),name = 'index'),
    path('diary/create/',views.DiaryCreateView.as_view(),name = 'diary_create'),
    path('diary/create/complete/',views.DiaryCreateCompleteView.as_view(),name = 'diary_create_complete'),
    path('diary/list/',views.DiaryListView.as_view(),name = 'diary_list'),
    ]

django0605/diary/models.py
from turtle import update
from django.db import models
from django.utils import timezone
import uuid

# Create your models here.
#日記フォーム：id,日付、タイトル、本文、作成日時、編集日時
class Diary(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)
    date = models.DateField(verbose_name='日付',default=timezone.now)
    title = models.CharField(verbose_name='タイトル',max_length=40)
    text = models.CharField(verbose_name='本文',max_length=200)
    created_at = models.DateTimeField(verbose_name='作成日時',default=timezone.now)
    updated_at = models.DateTimeField(verbose_name='更新日時',blank=True,null=True)

django0605/diary/forms.py
from django import forms
from .models import Diary

class DiaryForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('date','title','text')

django0605/diary/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,CreateView,ListView
from .forms import DiaryForm
from django.urls import reverse_lazy
from .models import Diary
# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

class DiaryCreateView(CreateView):
    template_name = 'diary_create.html'
    form_class = DiaryForm
    success_url = reverse_lazy('diary:diary_create_complete')

class DiaryCreateCompleteView(TemplateView):
    template_name = 'diary_create_complete.html'

class DiaryListView(ListView):
    template_name = 'diary_list.html'
    model = Diary

django0605/templates/diary_create.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <title>Diary App</title>
</head>
<body>
    <h1>Diary App by Django</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">投稿</button>
    </form>
</body>

</html>

django0605/templates/diary_create_complete.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <title>Diary App</title>
</head>
<body>
    <h1>Diary App by Django</h1>
    <p>日記の投稿が完了しました。</p>
    <a href="{% url 'diary:index' %}">トップへ戻る</a>
</body>

</html>

django0605/templates/diary_list.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <title>Diary App</title>
</head>
<body>
    <h1>Diary App by Django</h1>
    {% for diary in diary_list %}
    <p>
        {{ diary.date }}
        {{ diary.title }}
    </p>
    {% endfor %}
    <a href="{% url 'diary:index' %}">トップへ戻る</a>
</body>
</html>

django0605/templates/index.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8">
    <title>Diary App</title>
</head>
<body>
    <h1>Diary App by Django</h1>

    <a href="{% url 'diary:diary_create' %}">日記を投稿</a>
    <a href="{% url 'diary:diary_list' %}">日記を表示</a>
    <a href="https://github.com/yamamoto0107/pythonkaihatsu">github</a>
</body>

</html>